//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_framewk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Assignment1Entities : DbContext
    {
        public Assignment1Entities()
            : base("name=Assignment1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client_master> client_master { get; set; }
        public virtual DbSet<PRODUCT_MASTER> PRODUCT_MASTER { get; set; }
        public virtual DbSet<SALES_ORDER> SALES_ORDER { get; set; }
        public virtual DbSet<SALESMAN_MASTER> SALESMAN_MASTER { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
