//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_framewk
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESMAN_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALESMAN_MASTER()
        {
            this.SALES_ORDER = new HashSet<SALES_ORDER>();
        }
    
        public string SALESMANNO { get; set; }
        public string SALESMANNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public Nullable<decimal> PINCODE { get; set; }
        public string State { get; set; }
        public decimal SALAMT { get; set; }
        public decimal TGTTOGET { get; set; }
        public decimal YTDSALES { get; set; }
        public string REMARKS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_ORDER> SALES_ORDER { get; set; }
    }
}
